const styles = {
  container: {
    display: 'flex',
    flexDirection: 'row',
    width: '100%',
    height: '100%',
    backgroundColor: '#F5F5F5',
  },
  editorSection: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: '#FFFFFF',
    borderRight: '1px solid #E5E7EB',
  },
  imageListSection: {
    width: '300px',
    backgroundColor: '#FFFFFF',
    display: 'flex',
    flexDirection: 'column',
    overflowY: 'auto',
  },
  topToolbar: {
    padding: '12px 16px',
    borderBottom: '1px solid #E5E7EB',
    backgroundColor: '#FAFAFA',
  },
  toolbarRow: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  nameInputContainer: {
    width: '50%',
  },
  boardNameInput: {
    border: '1px solid #D1D5DB',
    borderRadius: '4px',
    padding: '8px 12px',
    fontSize: '14px',
    width: '100%',
    backgroundColor: '#FFFFFF',
    boxSizing: 'border-box',
  },
  maxCharLabel: {
    fontSize: '12px',
    color: '#6B7280',
    marginTop: '4px',
    display: 'block',
    textAlign: 'right',
  },
  actionButtons: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: '8px',
    flex: 1,
    justifyContent: 'flex-end',
  },
  transparencySection: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: '8px',
    marginRight: '16px',
  },
  transparencyLabel: {
    fontSize: '12px',
    color: '#374151',
    whiteSpace: 'nowrap',
  },
  transparencySlider: {
    width: '120px',
    height: '4px',
    borderRadius: '2px',
    background: '#E5E7EB',
    outline: 'none',
    cursor: 'pointer',
  },
  toolbarButton: {
    width: '32px',
    height: '32px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '4px',
    backgroundColor: 'transparent',
    border: 'none',
    cursor: 'pointer',
    fontSize: '16px',
  },
  canvasContainer: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '20px',
    overflow: 'auto',
    position: 'relative',
  },
  canvasWrapper: {
    borderRadius: '8px',
    border: '1px solid #E5E7EB',
    overflow: 'hidden',
    boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)',
  },
  imageGallery: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    padding: '16px',
    gap: '12px',
    overflowY: 'auto',
    flex: 1,
  },
  imageThumbnailWrapper: {
    width: 'calc(50% - 6px)',
    aspectRatio: '1',
    borderRadius: '8px',
    overflow: 'hidden',
    border: '2px solid #E5E7EB',
    cursor: 'pointer',
  },
  imageThumbnail: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  noImagesText: {
    padding: '20px',
    textAlign: 'center',
    color: '#666',
  },
};

export default styles;

